twc_enfants:
    resource: "@TWCEnfantsBundle/Resources/config/routing.yml"
    prefix:   /{_locale}/enfants

twc_parlement:
    resource: "@TWCParlementBundle/Resources/config/routing.yml"
    prefix:   /{_locale}/parlement

twc_congres:
    resource: "@TWCCongresBundle/Resources/config/routing.yml"
    prefix:   /{_locale}/congres

twc_ville:
    resource: "@TWCVilleBundle/Resources/config/routing.yml"
    prefix:   /{_locale}/ville

twc_onde:
    resource: "@TWCOndeBundle/Resources/config/routing.yml"
    prefix:   /{_locale}/
    requirements:
        _locale: '|en|fr|de|it|ar'
    options:
        expose: true