<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerGztqv6g\appProdProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerGztqv6g/appProdProjectContainer.php') {
    touch(__DIR__.'/ContainerGztqv6g.legacy');

    return;
}

if (!\class_exists(appProdProjectContainer::class, false)) {
    \class_alias(\ContainerGztqv6g\appProdProjectContainer::class, appProdProjectContainer::class, false);
}

return new \ContainerGztqv6g\appProdProjectContainer([
    'container.build_hash' => 'Gztqv6g',
    'container.build_id' => '1237d034',
    'container.build_time' => 1606832105,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerGztqv6g');
