<?php

namespace TWC\OndeBundle\Repository;

/**
 * OndeArticleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class OndeArticleRepository extends \Doctrine\ORM\EntityRepository
{
}
