<?php

namespace TWC\OndeBundle\Repository;

/**
 * OndePictureRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class OndePictureRepository extends \Doctrine\ORM\EntityRepository
{
}
