<?php

namespace TWC\OndeBundle\Repository;

/**
 * OndeMediaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class OndeMediaRepository extends \Doctrine\ORM\EntityRepository
{
}
