<?php

namespace TWC\OndeBundle\Repository;

/**
 * OndeImageRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class OndeImageRepository extends \Doctrine\ORM\EntityRepository
{
}
