<?php

namespace TWC\OndeBundle\Repository;

/**
 * OndeCategoriesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class OndeCategoriesRepository extends \Doctrine\ORM\EntityRepository
{
}
