<?php

namespace TWC\OndeBundle\Repository;

/**
 * OndeUserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class OndeUserRepository extends \Doctrine\ORM\EntityRepository
{
}
