<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'assetic.filter.sass' shared service.

include_once $this->targetDirs[3].'/vendor/kriswallsmith/assetic/src/Assetic/Filter/FilterInterface.php';
include_once $this->targetDirs[3].'/vendor/kriswallsmith/assetic/src/Assetic/Filter/BaseProcessFilter.php';
include_once $this->targetDirs[3].'/vendor/kriswallsmith/assetic/src/Assetic/Filter/DependencyExtractorInterface.php';
include_once $this->targetDirs[3].'/vendor/kriswallsmith/assetic/src/Assetic/Filter/Sass/BaseSassFilter.php';
include_once $this->targetDirs[3].'/vendor/kriswallsmith/assetic/src/Assetic/Filter/Sass/SassFilter.php';

$this->services['assetic.filter.sass'] = $instance = new \Assetic\Filter\Sass\SassFilter('/usr/bin/sass', '/usr/bin/ruby');

$instance->setTimeout(NULL);
$instance->setStyle(NULL);
$instance->setCompass(NULL);
$instance->setLoadPaths($this->getParameter('assetic.filter.sass.load_paths'));
$instance->setCacheLocation($this->targetDirs[0]);
$instance->setSourceMap(NULL);
$instance->setPrecision(NULL);

return $instance;
