<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'assetic.filter.compass' shared service.

include_once $this->targetDirs[3].'/vendor/kriswallsmith/assetic/src/Assetic/Filter/FilterInterface.php';
include_once $this->targetDirs[3].'/vendor/kriswallsmith/assetic/src/Assetic/Filter/BaseProcessFilter.php';
include_once $this->targetDirs[3].'/vendor/kriswallsmith/assetic/src/Assetic/Filter/DependencyExtractorInterface.php';
include_once $this->targetDirs[3].'/vendor/kriswallsmith/assetic/src/Assetic/Filter/Sass/BaseSassFilter.php';
include_once $this->targetDirs[3].'/vendor/kriswallsmith/assetic/src/Assetic/Filter/CompassFilter.php';

$this->services['assetic.filter.compass'] = $instance = new \Assetic\Filter\CompassFilter('/usr/bin/compass', '/usr/bin/ruby');

$instance->setScss(NULL);
$instance->setUnixNewlines(NULL);
$instance->setNoCache(NULL);
$instance->setForce(NULL);
$instance->setQuiet(NULL);
$instance->setTimeout(NULL);
$instance->setDebugInfo(false);
$instance->setBoring(true);
$instance->setNoLineComments(false);
$instance->setStyle(NULL);
$instance->setImagesDir(NULL);
$instance->setFontsDir(NULL);
$instance->setRelativeAssets(false);
$instance->setJavascriptsDir(NULL);
$instance->setHttpPath(NULL);
$instance->setHttpImagesPath(NULL);
$instance->setHttpFontsPath(NULL);
$instance->setHttpGeneratedImagesPath(NULL);
$instance->setGeneratedImagesPath(NULL);
$instance->setHttpJavascriptsPath(NULL);
$instance->setPlugins([]);
$instance->setLoadPaths([]);
$instance->setHomeEnv(true);
$instance->setCacheLocation($this->targetDirs[0]);

return $instance;
