twc_enfants_homepage:
    path:     /
    defaults: { _controller: TWCEnfantsBundle:Default:index }

index_presentation:
    path:     /indexP
    defaults: { _controller: TWCEnfantsBundle:Presentation:index }

index_droits:
    path:     /indexD
    defaults: { _controller: TWCEnfantsBundle:Droits:index }

index_jeux:
    path:     /indexJ
    defaults: { _controller: TWCEnfantsBundle:Jeux:index }

index_coloriage:
    path:     /indexC
    defaults: { _controller: TWCEnfantsBundle:Coloriage:index }

index_bd:
    path:     /indexB
    defaults: { _controller: TWCEnfantsBundle:BD:index }

index_videophoto:
    path:     /indexV
    defaults: { _controller: TWCEnfantsBundle:VideosPhotos:index }

formulaire:
    path:     /formulaire
    defaults: { _controller: TWCEnfantsBundle:Telechargement:formulaire }

brochure:
    path:     /brochure
    defaults: { _controller: TWCEnfantsBundle:Telechargement:brochure }

convention:
    path:     /convention
    defaults: { _controller: TWCEnfantsBundle:Telechargement:convention }
