<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerXtsami9\appDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerXtsami9/appDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerXtsami9.legacy');

    return;
}

if (!\class_exists(appDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerXtsami9\appDevDebugProjectContainer::class, appDevDebugProjectContainer::class, false);
}

return new \ContainerXtsami9\appDevDebugProjectContainer([
    'container.build_hash' => 'Xtsami9',
    'container.build_id' => '5f43049b',
    'container.build_time' => 1606831802,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerXtsami9');
